spring.datasource.url=jdbc:postgresql://localhost:5432/domidze_db?password=WgwwovOF92$&user=domidze_user
spring.jpa.hibernate.ddl-auto=create
rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem
logging.file.name=logs/domidzebot.log
logging.file.path=var/log/domidzebot
bot.enabled=false
calendar.amount.days.index=1
calendar.amount.weeks=8
appproperties.hash=djM7MT82MzYxgkA9iYtLdzeFSESCpzCuOptoS0mLMjKRT1dLRTEwUDBINk5rSzVFQDVFP4kzNjE9OTM2MTQzlUg2M001RT42SFE=
bot.name=ondedaybot
bot.token=7342451600:AAEFIvlLLNrib2mRTkmNWs3zUFWCbICzPIQ
bot.admin=187639790
calendar.scheduling.cron=0 0 * * * *