name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{vars.POSTGRESQL_DBNAME}}
          POSTGRES_USER: ${{vars.POSTGRESQL_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRESQL_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'corretto'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.11.1
          arguments: build

      - name: Run tests
        env:
          POSTGRESQL_HOST: ${{vars.POSTGRESQL_HOST}}
          POSTGRESQL_PORT: ${{vars.POSTGRESQL_PORT}}
          POSTGRESQL_DBNAME: ${{vars.POSTGRESQL_DBNAME}}
          POSTGRESQL_USER: ${{vars.POSTGRESQL_USER}}
          POSTGRESQL_PASSWORD: ${{secrets.POSTGRESQL_PASSWORD}}
        run: ./gradlew test

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: ./gradlew jacocoTestReport
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
